### ISSUE TITLE
Queue usage explanation

### ISSUE THREAD

**Issue by Tiboh** [philou/built-in-quality-game#9]
Hi,
Thank you for the great workshop idea ! I will try it with my team

In the rules of the game, there is not a lot of information of how the queue works.
- Do we put tickets in the queue if some tickets are in the previous column and if the current column is already full ?
- Can we choose if we want to drag tickets from the queue or from the previous column, or it's priority to the queue's column ?
- Why "it's not a good idea to pile work in queues" ?

**Comment by philou** [comment]
Added answers in the rules. Thanks for the questions
